# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@v2

      # node@14 runtime
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # validate compile、package
      - run: npm ci
      - run: npm run package
